name: .NET Build, Test & Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ./ByteFlow.Net/ByteFlow.sln

    - name: Build
      run: dotnet build ./ByteFlow.Net/ByteFlow.sln --no-restore --configuration Release

    - name: Test with coverage
      run: dotnet test ./ByteFlow.Net/ByteFlow.sln --no-build --configuration Release --collect:"XPlat Code Coverage"
